// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoReq struct {
	UserId int64 `json:"userId"`
}

type UserInfoResp struct {
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
}

type UserUpdateReq struct {
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
}

type UserUpdateResp struct {
	Flag bool `json:"flag"`
}

type UserCreateReq struct {
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
}

type UserCreateResp struct {
	Flag bool `json:"flag"`
}

type UserTestReq struct {
}

type UserTestResp struct {
}

type BasicIndexReq struct {
	Data string `json:"data"`
}

type BasicIndexResp struct {
	Msg string `json:"msg"`
}
