// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	basic "github.com/oublie6/oublie-zero-zoo/app/user-api/internal/handler/basic"
	user "github.com/oublie6/oublie-zero-zoo/app/user-api/internal/handler/user"
	"github.com/oublie6/oublie-zero-zoo/app/user-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TestMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/user/info",
					Handler: user.UserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/update",
					Handler: user.UserUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/create",
					Handler: user.UserCreateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/userapi/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/test",
				Handler: user.UserTestHandler(serverCtx),
			},
		},
		rest.WithPrefix("/userapi/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/index",
				Handler: basic.BasicIndexHandler(serverCtx),
			},
		},
	)
}
